
-- 1. Fix length taxonomy: add s6m, s65m, s7m entries
UPDATE home_content
SET data = jsonb_build_object('items', (
  SELECT jsonb_agg(item)
  FROM (
    SELECT item FROM jsonb_array_elements(data->'items') item
    UNION ALL
    SELECT '{"id":"s6m","value":"6M","label_he":"6 מטר","label_ar":"6 متر"}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jsonb_array_elements((SELECT data->'items' FROM home_content WHERE locale='global' AND section='length_taxonomy')) x WHERE x->>'id'='s6m')
    UNION ALL
    SELECT '{"id":"s65m","value":"6.5M","label_he":"6.5 מטר","label_ar":"6.5 متر"}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jsonb_array_elements((SELECT data->'items' FROM home_content WHERE locale='global' AND section='length_taxonomy')) x WHERE x->>'id'='s65m')
    UNION ALL
    SELECT '{"id":"s7m","value":"7M","label_he":"7 מטר","label_ar":"7 متر"}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jsonb_array_elements((SELECT data->'items' FROM home_content WHERE locale='global' AND section='length_taxonomy')) x WHERE x->>'id'='s7m')
  ) sub
))
WHERE locale = 'global' AND section = 'length_taxonomy';

-- 2. Update product_details for all Series 2000 products
UPDATE products SET product_details = '[{"label_he":"סוג פרופיל","label_ar":"نوع البروفيل","value_he":"עמוד נושא","value_ar":"عمود حامل"},{"label_he":"מידות חתך","label_ar":"أبعاد المقطع","value_he":"66×26 מ\"מ","value_ar":"66×26 ملم"},{"label_he":"חומר","label_ar":"المادة","value_he":"אלומיניום 6063-T5","value_ar":"ألمنيوم 6063-T5"},{"label_he":"עובי דופן","label_ar":"سماكة الجدار","value_he":"1.4 מ\"מ","value_ar":"1.4 ملم"},{"label_he":"אורך","label_ar":"الطول","value_he":"6 מטר","value_ar":"6 متر"},{"label_he":"משקל למטר","label_ar":"الوزن لكل متر","value_he":"1.15 ק\"ג","value_ar":"1.15 كجم"},{"label_he":"שימוש","label_ar":"الاستخدام","value_he":"עמוד תמיכה ראשי לפרגולות סדרה 2000","value_ar":"عمود دعم رئيسي لبرجولات سلسلة 2000"},{"label_he":"סידרה","label_ar":"السلسلة","value_he":"סדרה 2000","value_ar":"سلسلة 2000"}]'::jsonb WHERE sku = 'AMG-S2000-001';

UPDATE products SET product_details = '[{"label_he":"סוג פרופיל","label_ar":"نوع البروفيل","value_he":"הלבשה / כיסוי","value_ar":"تغليف / غطاء"},{"label_he":"חומר","label_ar":"المادة","value_he":"אלומיניום 6063-T5","value_ar":"ألمنيوم 6063-T5"},{"label_he":"עובי דופן","label_ar":"سماكة الجدار","value_he":"1.2 מ\"מ","value_ar":"1.2 ملم"},{"label_he":"אורך","label_ar":"الطول","value_he":"6 מטר","value_ar":"6 متر"},{"label_he":"משקל למטר","label_ar":"الوزن لكل متر","value_he":"0.65 ק\"ג","value_ar":"0.65 كجم"},{"label_he":"שימוש","label_ar":"الاستخدام","value_he":"כיסוי אסתטי לעמודים ומסגרות","value_ar":"تغطية جمالية للأعمدة والإطارات"},{"label_he":"סידרה","label_ar":"السلسلة","value_he":"סדרה 2000","value_ar":"سلسلة 2000"}]'::jsonb WHERE sku = 'AMG-S2000-002';

UPDATE products SET product_details = '[{"label_he":"סוג פרופיל","label_ar":"نوع البروفيل","value_he":"מכסה כפול ישר","value_ar":"غطاء مزدوج مستقيم"},{"label_he":"חומר","label_ar":"المادة","value_he":"אלומיניום 6063-T5","value_ar":"ألمنيوم 6063-T5"},{"label_he":"עובי דופן","label_ar":"سماكة الجدار","value_he":"1.2 מ\"מ","value_ar":"1.2 ملم"},{"label_he":"אורך","label_ar":"الطول","value_he":"6 מטר","value_ar":"6 متر"},{"label_he":"משקל למטר","label_ar":"الوزن لكل متر","value_he":"0.55 ק\"ג","value_ar":"0.55 كجم"},{"label_he":"שימוש","label_ar":"الاستخدام","value_he":"מכסה לחיבורים וקצוות פרופיל","value_ar":"غطاء للتوصيلات وأطراف البروفيل"},{"label_he":"סידרה","label_ar":"السلسلة","value_he":"סדרה 2000","value_ar":"سلسلة 2000"}]'::jsonb WHERE sku = 'AMG-S2000-003';

UPDATE products SET product_details = '[{"label_he":"סוג פרופיל","label_ar":"نوع البروفيل","value_he":"מכסה מעוגל (2455)","value_ar":"غطاء مقوس (2455)"},{"label_he":"חומר","label_ar":"المادة","value_he":"אלומיניום 6063-T5","value_ar":"ألمنيوم 6063-T5"},{"label_he":"עובי דופן","label_ar":"سماكة الجدار","value_he":"1.3 מ\"מ","value_ar":"1.3 ملم"},{"label_he":"אורך","label_ar":"الطول","value_he":"6 מטר","value_ar":"6 متر"},{"label_he":"משקל למטר","label_ar":"الوزن لكل متر","value_he":"0.60 ק\"ג","value_ar":"0.60 كجم"},{"label_he":"שימוש","label_ar":"الاستخدام","value_he":"מכסה עם קצה מעוגל לגימור אסתטי","value_ar":"غطاء بحافة مقوسة لتشطيب جمالي"},{"label_he":"סידרה","label_ar":"السلسلة","value_he":"סדרה 2000","value_ar":"سلسلة 2000"}]'::jsonb WHERE sku = 'AMG-S2000-004';

UPDATE products SET product_details = '[{"label_he":"סוג פרופיל","label_ar":"نوع البروفيل","value_he":"מכסה עם תעלת מברשת","value_ar":"غطاء مع قناة فرشاة"},{"label_he":"חומר","label_ar":"المادة","value_he":"אלומיניום 6063-T5","value_ar":"ألمنيوم 6063-T5"},{"label_he":"אורך","label_ar":"الطول","value_he":"6 מטר","value_ar":"6 متر"},{"label_he":"משקל למטר","label_ar":"الوزن لكل متر","value_he":"0.70 ק\"ג","value_ar":"0.70 كجم"},{"label_he":"שימוש","label_ar":"الاستخدام","value_he":"מכסה עם תעלה מובנית למברשת איטום","value_ar":"غطاء مع قناة مدمجة لفرشاة العزل"},{"label_he":"סידרה","label_ar":"السلسلة","value_he":"סדרה 2000","value_ar":"سلسلة 2000"}]'::jsonb WHERE sku = 'AMG-S2000-005';

UPDATE products SET product_details = '[{"label_he":"סוג פרופיל","label_ar":"نوع البروفيل","value_he":"מסעד יד למעקה","value_ar":"درابزين يد للسياج"},{"label_he":"חומר","label_ar":"المادة","value_he":"אלומיניום 6063-T5","value_ar":"ألمنيوم 6063-T5"},{"label_he":"עובי דופן","label_ar":"سماكة الجدار","value_he":"1.5 מ\"מ","value_ar":"1.5 ملم"},{"label_he":"אורך","label_ar":"الطول","value_he":"6 מטר","value_ar":"6 متر"},{"label_he":"משקל למטר","label_ar":"الوزن لكل متر","value_he":"1.80 ק\"ג","value_ar":"1.80 كجم"},{"label_he":"שימוש","label_ar":"الاستخدام","value_he":"מסעד יד ארגונומי למעקות בטיחות","value_ar":"درابزين يد مريح لسياج الأمان"},{"label_he":"סידרה","label_ar":"السلسلة","value_he":"סדרה 2000","value_ar":"سلسلة 2000"}]'::jsonb WHERE sku = 'AMG-S2000-006';

UPDATE products SET product_details = '[{"label_he":"סוג פרופיל","label_ar":"نوع البروفيل","value_he":"סרגל זיגוג ישר 26 מ\"מ","value_ar":"قضيب تزجيج مستقيم 26 ملم"},{"label_he":"מידות חתך","label_ar":"أبعاد المقطع","value_he":"26 מ\"מ רוחב","value_ar":"26 ملم عرض"},{"label_he":"חומר","label_ar":"المادة","value_he":"אלומיניום 6063-T5","value_ar":"ألمنيوم 6063-T5"},{"label_he":"אורך","label_ar":"الطول","value_he":"6-6.5 מטר","value_ar":"6-6.5 متر"},{"label_he":"משקל למטר","label_ar":"الوزن لكل متر","value_he":"0.45 ק\"ג","value_ar":"0.45 كجم"},{"label_he":"שימוש","label_ar":"الاستخدام","value_he":"סרגל להחזקת לוחות זכוכית ופוליקרבונט","value_ar":"قضيب لتثبيت ألواح الزجاج والبولي كربونات"},{"label_he":"סידרה","label_ar":"السلسلة","value_he":"סדרה 2000","value_ar":"سلسلة 2000"}]'::jsonb WHERE sku = 'AMG-S2000-007';

UPDATE products SET product_details = '[{"label_he":"סוג פרופיל","label_ar":"نوع البروفيل","value_he":"סרגל זיגוג ישר 14 מ\"מ","value_ar":"قضيب تزجيج مستقيم 14 ملم"},{"label_he":"מידות חתך","label_ar":"أبعاد المقطع","value_he":"14 מ\"מ רוחב","value_ar":"14 ملم عرض"},{"label_he":"חומר","label_ar":"المادة","value_he":"אלומיניום 6063-T5","value_ar":"ألمنيوم 6063-T5"},{"label_he":"אורך","label_ar":"الطول","value_he":"6 מטר","value_ar":"6 متر"},{"label_he":"משקל למטר","label_ar":"الوزن لكل متر","value_he":"0.30 ק\"ג","value_ar":"0.30 كجم"},{"label_he":"שימוש","label_ar":"الاستخدام","value_he":"סרגל זיגוג צר לפנלים דקים","value_ar":"قضيب تزجيج ضيق للألواح الرقيقة"},{"label_he":"סידרה","label_ar":"السلسلة","value_he":"סדרה 2000","value_ar":"سلسلة 2000"}]'::jsonb WHERE sku = 'AMG-S2000-008';

UPDATE products SET product_details = '[{"label_he":"סוג פרופיל","label_ar":"نوع البروفيل","value_he":"סרגל זיגוג ישר 15 מ\"מ","value_ar":"قضيب تزجيج مستقيم 15 ملم"},{"label_he":"מידות חתך","label_ar":"أبعاد المقطع","value_he":"15 מ\"מ רוחב","value_ar":"15 ملم عرض"},{"label_he":"חומר","label_ar":"المادة","value_he":"אלומיניום 6063-T5","value_ar":"ألمنيوم 6063-T5"},{"label_he":"אורך","label_ar":"الطول","value_he":"6 מטר","value_ar":"6 متر"},{"label_he":"משקל למטר","label_ar":"الوزن لكل متر","value_he":"0.35 ק\"ג","value_ar":"0.35 كجم"},{"label_he":"שימוש","label_ar":"الاستخدام","value_he":"סרגל זיגוג סטנדרטי","value_ar":"قضيب تزجيج قياسي"},{"label_he":"סידרה","label_ar":"السلسلة","value_he":"סדרה 2000","value_ar":"سلسلة 2000"}]'::jsonb WHERE sku = 'AMG-S2000-009';

UPDATE products SET product_details = '[{"label_he":"סוג פרופיל","label_ar":"نوع البروفيل","value_he":"סרגל זיגוג / בידודית למעקה","value_ar":"قضيب تزجيج / عازل للسياج"},{"label_he":"מידות חתך","label_ar":"أبعاد المقطع","value_he":"26 מ\"מ / 120 מ\"מ מלבני","value_ar":"26 ملم / 120 ملم مستطيل"},{"label_he":"חומר","label_ar":"المادة","value_he":"אלומיניום 6063-T5","value_ar":"ألمنيوم 6063-T5"},{"label_he":"אורך","label_ar":"الطول","value_he":"6 מטר","value_ar":"6 متر"},{"label_he":"שימוש","label_ar":"الاستخدام","value_he":"סרגל דו-שימושי לזיגוג ולבידוד מעקות","value_ar":"قضيب ثنائي الاستخدام للتزجيج وعزل السياج"},{"label_he":"סידרה","label_ar":"السلسلة","value_he":"סדרה 2000","value_ar":"سلسلة 2000"}]'::jsonb WHERE sku = 'AMG-S2000-010';

UPDATE products SET product_details = '[{"label_he":"סוג פרופיל","label_ar":"نوع البروفيل","value_he":"סרגל זיגוג משופע (גבוה)","value_ar":"قضيب تزجيج مائل (مرتفع)"},{"label_he":"חומר","label_ar":"المادة","value_he":"אלומיניום 6063-T5","value_ar":"ألمنيوم 6063-T5"},{"label_he":"אורך","label_ar":"الطول","value_he":"6-7 מטר","value_ar":"6-7 متر"},{"label_he":"משקל למטר","label_ar":"الوزن لكل متر","value_he":"0.50 ק\"ג","value_ar":"0.50 كجم"},{"label_he":"שימוש","label_ar":"الاستخدام","value_he":"סרגל זיגוג בזווית לגגות משופעים","value_ar":"قضيب تزجيج بزاوية للأسقف المائلة"},{"label_he":"סידרה","label_ar":"السلسلة","value_he":"סדרה 2000","value_ar":"سلسلة 2000"}]'::jsonb WHERE sku = 'AMG-S2000-011';

UPDATE products SET product_details = '[{"label_he":"סוג פרופיל","label_ar":"نوع البروفيل","value_he":"סרגל זיגוג משופע 22 מ\"מ בידודית","value_ar":"قضيب تزجيج مائل 22 ملم عازل"},{"label_he":"מידות חתך","label_ar":"أبعاد المقطع","value_he":"22 מ\"מ","value_ar":"22 ملم"},{"label_he":"חומר","label_ar":"المادة","value_he":"אלומיניום 6063-T5","value_ar":"ألمنيوم 6063-T5"},{"label_he":"אורך","label_ar":"الطول","value_he":"6 מטר","value_ar":"6 متر"},{"label_he":"שימוש","label_ar":"الاستخدام","value_he":"סרגל משופע עם בידוד תרמי","value_ar":"قضيب مائل مع عزل حراري"},{"label_he":"סידרה","label_ar":"السلسلة","value_he":"סדרה 2000","value_ar":"سلسلة 2000"}]'::jsonb WHERE sku = 'AMG-S2000-012';

UPDATE products SET product_details = '[{"label_he":"סוג פרופיל","label_ar":"نوع البروفيل","value_he":"סרגל זיגוג משופע קצר","value_ar":"قضيب تزجيج مائل قصير"},{"label_he":"חומר","label_ar":"المادة","value_he":"אלומיניום 6063-T5","value_ar":"ألمنيوم 6063-T5"},{"label_he":"אורך","label_ar":"الطول","value_he":"6-7 מטר","value_ar":"6-7 متر"},{"label_he":"חיבור","label_ar":"التوصيل","value_he":"מתחבר ל-YSL004","value_ar":"يتصل بـ YSL004"},{"label_he":"שימוש","label_ar":"الاستخدام","value_he":"סרגל משופע קצר למעברים וחיבורים","value_ar":"قضيب مائل قصير للممرات والتوصيلات"},{"label_he":"סידרה","label_ar":"السلسلة","value_he":"סדרה 2000","value_ar":"سلسلة 2000"}]'::jsonb WHERE sku = 'AMG-S2000-013';

UPDATE products SET product_details = '[{"label_he":"סוג פרופיל","label_ar":"نوع البروفيل","value_he":"סרגל זיגוג עגול (KST)","value_ar":"قضيب تزجيج دائري (KST)"},{"label_he":"חומר","label_ar":"المادة","value_he":"אלומיניום 6063-T5","value_ar":"ألمنيوم 6063-T5"},{"label_he":"אורך","label_ar":"الطول","value_he":"6-6.5 מטר","value_ar":"6-6.5 متر"},{"label_he":"משקל למטר","label_ar":"الوزن لكل متر","value_he":"0.40 ק\"ג","value_ar":"0.40 كجم"},{"label_he":"שימוש","label_ar":"الاستخدام","value_he":"סרגל עם פרופיל עגול לגימור חלק","value_ar":"قضيب بمقطع دائري لتشطيب ناعم"},{"label_he":"סידרה","label_ar":"السلسلة","value_he":"סדרה 2000","value_ar":"سلسلة 2000"}]'::jsonb WHERE sku = 'AMG-S2000-014';

UPDATE products SET product_details = '[{"label_he":"סוג פרופיל","label_ar":"نوع البروفيل","value_he":"עמוד 100×66","value_ar":"عمود 100×66"},{"label_he":"מידות חתך","label_ar":"أبعاد المقطع","value_he":"100×66 מ\"מ","value_ar":"100×66 ملم"},{"label_he":"חומר","label_ar":"المادة","value_he":"אלומיניום 6063-T5","value_ar":"ألمنيوم 6063-T5"},{"label_he":"עובי דופן","label_ar":"سماكة الجدار","value_he":"1.8 מ\"מ","value_ar":"1.8 ملم"},{"label_he":"אורך","label_ar":"الطول","value_he":"6 מטר","value_ar":"6 متر"},{"label_he":"משקל למטר","label_ar":"الوزن لكل متر","value_he":"2.20 ק\"ג","value_ar":"2.20 كجم"},{"label_he":"שימוש","label_ar":"الاستخدام","value_he":"עמוד תמיכה כבד לפרגולות גדולות","value_ar":"عمود دعم ثقيل للبرجولات الكبيرة"},{"label_he":"סידרה","label_ar":"السلسلة","value_he":"סדרה 2000","value_ar":"سلسلة 2000"}]'::jsonb WHERE sku = 'AMG-S2000-015';

UPDATE products SET product_details = '[{"label_he":"סוג פרופיל","label_ar":"نوع البروفيل","value_he":"עמוד 120×40","value_ar":"عمود 120×40"},{"label_he":"מידות חתך","label_ar":"أبعاد المقطع","value_he":"120×40 מ\"מ","value_ar":"120×40 ملم"},{"label_he":"חומר","label_ar":"المادة","value_he":"אלומיניום 6063-T5","value_ar":"ألمنيوم 6063-T5"},{"label_he":"עובי דופן","label_ar":"سماكة الجدار","value_he":"1.6 מ\"מ","value_ar":"1.6 ملم"},{"label_he":"אורך","label_ar":"الطول","value_he":"6 מטר","value_ar":"6 متر"},{"label_he":"משקל למטר","label_ar":"الوزن لكل متر","value_he":"2.50 ק\"ג","value_ar":"2.50 كجم"},{"label_he":"שימוש","label_ar":"الاستخدام","value_he":"עמוד בפרופיל רחב למעקות ומסגרות","value_ar":"عمود بمقطع عريض للسياج والإطارات"},{"label_he":"סידרה","label_ar":"السلسلة","value_he":"סדרה 2000","value_ar":"سلسلة 2000"}]'::jsonb WHERE sku = 'AMG-S2000-016';

UPDATE products SET product_details = '[{"label_he":"סוג פרופיל","label_ar":"نوع البروفيل","value_he":"עמוד 125×66","value_ar":"عمود 125×66"},{"label_he":"מידות חתך","label_ar":"أبعاد المقطع","value_he":"125×66 מ\"מ","value_ar":"125×66 ملم"},{"label_he":"חומר","label_ar":"المادة","value_he":"אלומיניום 6063-T5","value_ar":"ألمنيوم 6063-T5"},{"label_he":"עובי דופן","label_ar":"سماكة الجدار","value_he":"2.0 מ\"מ","value_ar":"2.0 ملم"},{"label_he":"אורך","label_ar":"الطول","value_he":"6 מטר","value_ar":"6 متر"},{"label_he":"משקל למטר","label_ar":"الوزن لكل متر","value_he":"2.80 ק\"ג","value_ar":"2.80 كجم"},{"label_he":"שימוש","label_ar":"الاستخدام","value_he":"עמוד כבד למבנים גדולים","value_ar":"عمود ثقيل للمنشآت الكبيرة"},{"label_he":"סידרה","label_ar":"السلسلة","value_he":"סדרה 2000","value_ar":"سلسلة 2000"}]'::jsonb WHERE sku = 'AMG-S2000-017';

UPDATE products SET product_details = '[{"label_he":"סוג פרופיל","label_ar":"نوع البروفيل","value_he":"עמוד 66×18","value_ar":"عمود 66×18"},{"label_he":"מידות חתך","label_ar":"أبعاد المقطع","value_he":"66×18 מ\"מ","value_ar":"66×18 ملم"},{"label_he":"חומר","label_ar":"المادة","value_he":"אלומיניום 6063-T5","value_ar":"ألمنيوم 6063-T5"},{"label_he":"עובי דופן","label_ar":"سماكة الجدار","value_he":"1.2 מ\"מ","value_ar":"1.2 ملم"},{"label_he":"אורך","label_ar":"الطول","value_he":"6 מטר","value_ar":"6 متر"},{"label_he":"משקל למטר","label_ar":"الوزن لكل متر","value_he":"1.05 ק\"ג","value_ar":"1.05 كجم"},{"label_he":"שימוש","label_ar":"الاستخدام","value_he":"עמוד דק לשערים קלים ומעקות","value_ar":"عمود رفيع للبوابات الخفيفة والسياج"},{"label_he":"סידרה","label_ar":"السلسلة","value_he":"סדרה 2000","value_ar":"سلسلة 2000"}]'::jsonb WHERE sku = 'AMG-S2000-018';

UPDATE products SET product_details = '[{"label_he":"סוג פרופיל","label_ar":"نوع البروفيل","value_he":"עמוד 66×40","value_ar":"عمود 66×40"},{"label_he":"מידות חתך","label_ar":"أبعاد المقطع","value_he":"66×40 מ\"מ","value_ar":"66×40 ملم"},{"label_he":"חומר","label_ar":"المادة","value_he":"אלומיניום 6063-T5","value_ar":"ألمنيوم 6063-T5"},{"label_he":"עובי דופן","label_ar":"سماكة الجدار","value_he":"1.5 מ\"מ","value_ar":"1.5 ملم"},{"label_he":"אורך","label_ar":"الطول","value_he":"6-7 מטר","value_ar":"6-7 متر"},{"label_he":"משקל למטר","label_ar":"الوزن لكل متر","value_he":"1.45 ק\"ג","value_ar":"1.45 كجم"},{"label_he":"שימוש","label_ar":"الاستخدام","value_he":"עמוד רב-שימושי לשערים ופרגולות","value_ar":"عمود متعدد الاستخدامات للبوابات والبرجولات"},{"label_he":"סידרה","label_ar":"السلسלة","value_he":"סדרה 2000","value_ar":"سلسلة 2000"}]'::jsonb WHERE sku = 'AMG-S2000-019';

UPDATE products SET product_details = '[{"label_he":"סוג פרופיל","label_ar":"نوع البروفيل","value_he":"עמוד 66×66","value_ar":"عمود 66×66"},{"label_he":"מידות חתך","label_ar":"أبعاد المقطع","value_he":"66×66 מ\"מ","value_ar":"66×66 ملم"},{"label_he":"חומר","label_ar":"المادة","value_he":"אלומיניום 6063-T5","value_ar":"ألمنيوم 6063-T5"},{"label_he":"עובי דופן","label_ar":"سماكة الجدار","value_he":"1.6 מ\"מ","value_ar":"1.6 ملم"},{"label_he":"אורך","label_ar":"الطول","value_he":"6-6.5 מטר","value_ar":"6-6.5 متر"},{"label_he":"משקל למטר","label_ar":"الوزن لكل متر","value_he":"1.90 ק\"ג","value_ar":"1.90 كجم"},{"label_he":"שימוש","label_ar":"الاستخدام","value_he":"עמוד ריבועי לפרגולות ומעקות","value_ar":"عمود مربع للبرجولات والسياج"},{"label_he":"סידרה","label_ar":"السلسلة","value_he":"סדרה 2000","value_ar":"سلسلة 2000"}]'::jsonb WHERE sku = 'AMG-S2000-020';

UPDATE products SET product_details = '[{"label_he":"סוג פרופיל","label_ar":"نوع البروفيل","value_he":"עמוד/קורה עגולה 86/55","value_ar":"عمود/كمرة دائرية 86/55"},{"label_he":"מידות חתך","label_ar":"أبعاد المقطع","value_he":"קוטר 86/55 מ\"מ","value_ar":"قطر 86/55 ملم"},{"label_he":"חומר","label_ar":"المادة","value_he":"אלומיניום 6063-T5","value_ar":"ألمنيوم 6063-T5"},{"label_he":"עובי דופן","label_ar":"سماكة الجدار","value_he":"2.0 מ\"מ","value_ar":"2.0 ملم"},{"label_he":"אורך","label_ar":"الطول","value_he":"6 מטר","value_ar":"6 متر"},{"label_he":"משקל למטר","label_ar":"الوزن لكل متر","value_he":"2.40 ק\"ג","value_ar":"2.40 كجم"},{"label_he":"שימוש","label_ar":"الاستخدام","value_he":"עמוד או קורה בפרופיל עגול","value_ar":"عمود أو كمرة بمقطع دائري"},{"label_he":"סידרה","label_ar":"السלسלة","value_he":"סדרה 2000","value_ar":"سلسلة 2000"}]'::jsonb WHERE sku = 'AMG-S2000-021';

UPDATE products SET product_details = '[{"label_he":"סוג פרופיל","label_ar":"نوع البروفيل","value_he":"פינה מתכוננת (זכר)","value_ar":"زاوية قابلة للتعديل (ذكر)"},{"label_he":"חומר","label_ar":"المادة","value_he":"אלומיניום 6063-T5","value_ar":"ألمنيوم 6063-T5"},{"label_he":"אורך","label_ar":"الطول","value_he":"6 מטר","value_ar":"6 متر"},{"label_he":"שימוש","label_ar":"الاستخدام","value_he":"חלק ב של פינה מתכוננת","value_ar":"الجزء الثاني من الزاوية القابلة للتعديل"},{"label_he":"סידרה","label_ar":"السلسلة","value_he":"סדרה 2000","value_ar":"سلسلة 2000"}]'::jsonb WHERE sku = 'AMG-S2000-022';

UPDATE products SET product_details = '[{"label_he":"סוג פרופיל","label_ar":"نوع البروفيل","value_he":"פינה מתכוננת (נקבה)","value_ar":"زاوية قابلة للتعديل (أنثى)"},{"label_he":"חומר","label_ar":"المادة","value_he":"אלומיניום 6063-T5","value_ar":"ألمنيوم 6063-T5"},{"label_he":"אורך","label_ar":"الطول","value_he":"6 מטר","value_ar":"6 متر"},{"label_he":"שימוש","label_ar":"الاستخدام","value_he":"חלק א של פינה מתכוננת","value_ar":"الجزء الأول من الزاوية القابلة للتعديل"},{"label_he":"סידרה","label_ar":"السלسلة","value_he":"סדרה 2000","value_ar":"سلسلة 2000"}]'::jsonb WHERE sku = 'AMG-S2000-023';

UPDATE products SET product_details = '[{"label_he":"סוג פרופיל","label_ar":"نوع البروفيل","value_he":"פרופיל חיבור 90°","value_ar":"بروفيل توصيل 90°"},{"label_he":"חומר","label_ar":"المادة","value_he":"אלומיניום 6063-T5","value_ar":"ألمنيوم 6063-T5"},{"label_he":"אורך","label_ar":"الطول","value_he":"6 מטר","value_ar":"6 متر"},{"label_he":"משקל למטר","label_ar":"الوزن لكل متر","value_he":"1.30 ק\"ג","value_ar":"1.30 كجم"},{"label_he":"שימוש","label_ar":"الاستخدام","value_he":"חיבור שני פרופילים בזווית 90 מעלות","value_ar":"توصيل بروفيلين بزاوية 90 درجة"},{"label_he":"סידרה","label_ar":"السלسלة","value_he":"סדרה 2000","value_ar":"سلسلة 2000"}]'::jsonb WHERE sku = 'AMG-S2000-024';

UPDATE products SET product_details = '[{"label_he":"סוג פרופיל","label_ar":"نوع البروفيل","value_he":"פרופיל חיבור פינה","value_ar":"بروفيل توصيل زاوية"},{"label_he":"חומר","label_ar":"المادة","value_he":"אלומיניום 6063-T5","value_ar":"ألمنيوم 6063-T5"},{"label_he":"אורך","label_ar":"الطول","value_he":"6 מטר","value_ar":"6 متر"},{"label_he":"משקל למטר","label_ar":"الوزن لكل متر","value_he":"2.60 ק\"ג","value_ar":"2.60 كجم"},{"label_he":"שימוש","label_ar":"الاستخدام","value_he":"חיבור פרופילים בפינות מבנה","value_ar":"توصيل البروفيلات في زوايا المنشأة"},{"label_he":"סידרה","label_ar":"السلسلة","value_he":"סדרה 2000","value_ar":"سلسلة 2000"}]'::jsonb WHERE sku = 'AMG-S2000-025';

UPDATE products SET product_details = '[{"label_he":"סוג פרופיל","label_ar":"نوع البروفيل","value_he":"פרופיל מעבר למונובלוק 30","value_ar":"بروفيل انتقال مونوبلوك 30"},{"label_he":"חומר","label_ar":"المادة","value_he":"אלומיניום 6063-T5","value_ar":"ألمنيوم 6063-T5"},{"label_he":"אורך","label_ar":"الطول","value_he":"6 מטר","value_ar":"6 متر"},{"label_he":"משקל למטר","label_ar":"الوزن لكل متر","value_he":"1.25 ק\"ג","value_ar":"1.25 كجم"},{"label_he":"שימוש","label_ar":"الاستخدام","value_he":"חיבור מעבר לפרופילי מונובלוק","value_ar":"وصلة انتقالية لبروفيلات المونوبلوك"},{"label_he":"סידרה","label_ar":"السלسلة","value_he":"סדרה 2000","value_ar":"سلسلة 2000"}]'::jsonb WHERE sku = 'AMG-S2000-026';

UPDATE products SET product_details = '[{"label_he":"סוג פרופיל","label_ar":"نوع البروفيل","value_he":"פרופיל רבע עגול 27.6×27.6","value_ar":"بروفيل ربع دائري 27.6×27.6"},{"label_he":"מידות חתך","label_ar":"أبعاد المقطع","value_he":"27.6×27.6 מ\"מ","value_ar":"27.6×27.6 ملم"},{"label_he":"חומר","label_ar":"المادة","value_he":"אלומיניום 6063-T5","value_ar":"ألمنيوم 6063-T5"},{"label_he":"אורך","label_ar":"الطول","value_he":"6 מטר","value_ar":"6 متر"},{"label_he":"משקל למטר","label_ar":"الوزن لكل متر","value_he":"0.55 ק\"ג","value_ar":"0.55 كجم"},{"label_he":"שימוש","label_ar":"الاستخدام","value_he":"פרופיל עיצובי לגימור פינות","value_ar":"بروفيل تصميمي لتشطيب الزوايا"},{"label_he":"סידרה","label_ar":"السلسلة","value_he":"סדרה 2000","value_ar":"سلسلة 2000"}]'::jsonb WHERE sku = 'AMG-S2000-027';

UPDATE products SET product_details = '[{"label_he":"סוג פרופיל","label_ar":"نوع البروفيل","value_he":"שולב","value_ar":"شولب"},{"label_he":"חומר","label_ar":"المادة","value_he":"אלומיניום 6063-T5","value_ar":"ألمنيوم 6063-T5"},{"label_he":"אורך","label_ar":"الطول","value_he":"6 מטר","value_ar":"6 متر"},{"label_he":"משקל למטר","label_ar":"الوزن لكل متر","value_he":"0.85 ק\"ג","value_ar":"0.85 كجم"},{"label_he":"שימוש","label_ar":"الاستخدام","value_he":"חיבור ושילוב בין פרופילים שונים","value_ar":"وصل ودمج بين البروفيلات المختلفة"},{"label_he":"סידרה","label_ar":"السلسلة","value_he":"סדרה 2000","value_ar":"سلسلة 2000"}]'::jsonb WHERE sku = 'AMG-S2000-028';

UPDATE products SET product_details = '[{"label_he":"סוג פרופיל","label_ar":"نوع البروفيل","value_he":"שולב מברשת (מפגש דלת)","value_ar":"شولب فرشاة (التقاء باب)"},{"label_he":"חומר","label_ar":"المادة","value_he":"אלומיניום 6063-T5","value_ar":"ألمنيوم 6063-T5"},{"label_he":"אורך","label_ar":"الطول","value_he":"6 מטר","value_ar":"6 متر"},{"label_he":"משקל למטר","label_ar":"الوزن لكل متر","value_he":"0.80 ק\"ג","value_ar":"0.80 كجم"},{"label_he":"שימוש","label_ar":"الاستخدام","value_he":"פרופיל מפגש עם תעלת מברשת לדלתות","value_ar":"بروفيل التقاء مع قناة فرشاة للأبواب"},{"label_he":"סידרה","label_ar":"السلسلة","value_he":"סדרה 2000","value_ar":"سلسلة 2000"}]'::jsonb WHERE sku = 'AMG-S2000-029';

UPDATE products SET product_details = '[{"label_he":"סוג פרופיל","label_ar":"نوع البروفيل","value_he":"שלב 10","value_ar":"درجة 10"},{"label_he":"חומר","label_ar":"المادة","value_he":"אלומיניום 6063-T5","value_ar":"ألمنيوم 6063-T5"},{"label_he":"אורך","label_ar":"الطول","value_he":"6 מטר","value_ar":"6 متر"},{"label_he":"משקל למטר","label_ar":"الوزن لكل متر","value_he":"0.95 ק\"ג","value_ar":"0.95 كجم"},{"label_he":"שימוש","label_ar":"الاستخدام","value_he":"פרופיל שלב למדרגות ומשטחים","value_ar":"بروفيل درجة للسلالم والأسطح"},{"label_he":"סידרה","label_ar":"السلسلة","value_he":"סדרה 2000","value_ar":"سلسلة 2000"}]'::jsonb WHERE sku = 'AMG-S2000-030';

UPDATE products SET product_details = '[{"label_he":"סוג פרופיל","label_ar":"نوع البروفيل","value_he":"תושבת לפרופיל","value_ar":"قاعدة للبروفيل"},{"label_he":"חומר","label_ar":"المادة","value_he":"אלומיניום 6063-T5","value_ar":"ألمنيوم 6063-T5"},{"label_he":"אורך","label_ar":"الطول","value_he":"6 מטר","value_ar":"6 متر"},{"label_he":"משקל למטר","label_ar":"الوزن لكل متر","value_he":"0.75 ק\"ג","value_ar":"0.75 كجم"},{"label_he":"שימוש","label_ar":"الاستخدام","value_he":"תושבת בסיס לחיבור פרופילים למשטח","value_ar":"قاعدة أساس لتثبيت البروفيلات على السطح"},{"label_he":"סידרה","label_ar":"السلسלة","value_he":"סדרה 2000","value_ar":"سلسلة 2000"}]'::jsonb WHERE sku = 'AMG-S2000-031';

-- 3. Update content_html for HE translations
UPDATE product_translations SET content_html = '<div class="space-y-6"><div class="bg-gray-50 rounded-xl p-6"><h3 class="text-lg font-bold mb-3">מפרט טכני</h3><p>פרופיל אלומיניום מסדרה 2000 של AMG Pergola. מיוצר מאלומיניום 6063-T5 באיכות פרימיום, מתאים לשימוש חיצוני בתנאי מזג אוויר קשים. הפרופיל עובר תהליך אנודייז או צביעה אלקטרוסטטית להגנה מירבית מפני קורוזיה.</p></div><div class="bg-gray-50 rounded-xl p-6"><h3 class="text-lg font-bold mb-3">יתרונות</h3><ul class="list-disc list-inside space-y-2 text-gray-700"><li>עמידות גבוהה בפני קורוזיה ושחיקה</li><li>משקל קל יחסית לחוזק המכני</li><li>מגוון צבעים וגימורים זמינים</li><li>התקנה פשוטה ומהירה</li><li>אחריות יצרן למשך 10 שנים</li><li>תחזוקה מינימלית</li></ul></div><div class="bg-gray-50 rounded-xl p-6"><h3 class="text-lg font-bold mb-3">הנחיות התקנה</h3><p>יש לבצע חיתוך באמצעות מסור דיסק עם להב מתאים לאלומיניום. מומלץ להשתמש בברגי נירוסטה למניעת קורוזיה גלוונית. יש להקפיד על מרווחי התפשטות תרמית בהתאם להנחיות היצרן.</p></div></div>'
WHERE locale = 'he' AND product_id IN (SELECT id FROM products WHERE category_id = '8807c168-cfd0-47a1-9b00-42f16b2fc9f5');

-- 4. Update content_html for AR translations
UPDATE product_translations SET content_html = '<div class="space-y-6"><div class="bg-gray-50 rounded-xl p-6"><h3 class="text-lg font-bold mb-3">المواصفات التقنية</h3><p>بروفيل ألمنيوم من سلسلة 2000 من AMG Pergola. مصنوع من ألمنيوم 6063-T5 بجودة ممتازة، مناسب للاستخدام الخارجي في ظروف مناخية قاسية. يخضع البروفيل لعملية أنودة أو طلاء إلكتروستاتيكي لحماية قصوى من التآكل.</p></div><div class="bg-gray-50 rounded-xl p-6"><h3 class="text-lg font-bold mb-3">المميزات</h3><ul class="list-disc list-inside space-y-2 text-gray-700"><li>مقاومة عالية للتآكل والتلف</li><li>وزن خفيف نسبياً مقارنة بالمتانة الميكانيكية</li><li>مجموعة متنوعة من الألوان والتشطيبات المتاحة</li><li>تركيب سهل وسريع</li><li>ضمان المصنع لمدة 10 سنوات</li><li>صيانة بسيطة</li></ul></div><div class="bg-gray-50 rounded-xl p-6"><h3 class="text-lg font-bold mb-3">تعليمات التركيب</h3><p>يجب القطع باستخدام منشار قرصي بشفرة مناسبة للألمنيوم. يوصى باستخدام براغي من الفولاذ المقاوم للصدأ لمنع التآكل الجلفاني. يجب مراعاة فجوات التمدد الحراري وفقاً لتعليمات الشركة المصنعة.</p></div></div>'
WHERE locale = 'ar' AND product_id IN (SELECT id FROM products WHERE category_id = '8807c168-cfd0-47a1-9b00-42f16b2fc9f5');
