
ALTER TABLE public.pergola_requests
  ADD COLUMN IF NOT EXISTS quoted_price NUMERIC DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS admin_response_sent_at TIMESTAMPTZ DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS response_token TEXT DEFAULT NULL;
